# Generated by Django 6.0.1 on 2026-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
